language: php
php:
   - 7.4
script: ./build.sh
before_install:
  - chmod +x build.sh
branches:
  only:
  - develop
deploy:
  edge: true
  provider: cloudfoundry
  username: adrian.milne@crowncommercial.gov.uk
  api: https://api.london.cloud.service.gov.uk
  organization: ccs-scale-cat
  space: sandbox
  buildpack: https://github.com/cloudfoundry/php-buildpack.git
  on:
    branch: develop
  password:
    secure: GcuA3haLhWGx6nRGGC5plXZJJKHyhGayk9ZGW/qMkISHNoPmjkvIqwpapZeI0HMEIKKhvT3gvltbB8fmUrkerUIEV6B/Ki3WF4K7jOO/cVGsBMKoqqTYwZ5YQNl1mW9ohp5sOzyvTz2gEQQaD8yVxpKlB2A/0fnH6NVlDqb9vMQJjQK5d2UOCcy4KbEYwcw4mjuzEJtAC5LkKndgBGT1iXY3wUbN8rbEr/q24XCnvM2HMHFPDIIaCWHmg9uSKNChyEfI1ZlYzlgIwbSsfBDIR4QyhKDxUlvKh1UKB56xIIi9Zv5eZcPnnJwNpFHk2sPfJHCsqI7tN1ZebBKZvPzlOznHdxbNC1oAr6JbgL1+P9uCwarEXT1PzyHqYDGtYUDY/YjnUJDHJ79LR50v6ebvYaCbx7mT2weY72hMlVIHMBITSVzPMKbkhC9kBI482igk47elHVEbL7Nu+6lU1PqBpUYvJaqD0dEWvenuwUc8dqKBTUJ/xGJqPkin1K18HyfkAhlRP8B+w5eSTjQyy+XqwD6Cs1QYuYKU03vRum8qKkKkrPGrceNjkWau4OEPICpxxQtMqQzns42nzBZo9OPj/+YoeEU4L0byRCe93QqCtvyo7/Lq7FIQPolTWrQXUsusKBCwa8O1fJF/OBqZd/LfkNm+MDPgrXRrjytdDRwZgQU=
